dataset:
  name: "idol"
  type: "AvatarDataset"
  
  # 数据集路径配置
  data_prefix: "/path/to/idol/dataset"
  cache_path: "/path/to/idol/cache.npy"
  
  # 图像配置
  img_res: [640, 896]
  radius: 1.0
  
  # 数据集参数
  load_imgs: true
  load_norm: false
  load_cond_data: true
  load_test_data: true
  num_train_imgs: -1
  max_num_scenes: -1
  
  # 视角配置
  specific_observation_idcs: null
  specific_observation_num: null
  first_is_front: false
  better_range: false
  random_test_imgs: false
  
  # 视频参考图像配置
  if_include_video_ref_img: false
  prob_include_video_ref_img: 0.2
  allow_k_angles_near_the_front: 0
  
  # 其他配置
  scene_id_as_name: false
  test_mode: false
  step: 1
  crop: false
  
  # 设备配置
  device: "cuda" 