dataset:
  name: "idol"
  type: "IDOLDataset"
  
  # 数据集路径配置
  data_prefix: null
  cache_path_train: [
    "/disk2/liubingqi/work/data/IDOL/processed_data/flux_batch8_train_17483.npy",
    "/disk2/liubingqi/work/data/IDOL/processed_data/flux_batch9_train_13425.npy"
  ]
  cache_path_val: [
    "/disk2/liubingqi/work/data/IDOL/processed_data/flux_batch8_val_10.npy",
    "/disk2/liubingqi/work/data/IDOL/processed_data/flux_batch9_val_10.npy"
  ]
  cache_path_test: [
    "/disk2/liubingqi/work/data/IDOL/processed_data/flux_batch8_test_50.npy",
    "/disk2/liubingqi/work/data/IDOL/processed_data/flux_batch9_test_50.npy"
  ]
  # 图像配置
  image_size: [896, 640]
  
  # 视角配置
  specific_observation_num: 8
  first_is_front: true
  better_range: true
  
  # 视频参考图像配置
  if_include_video_ref_img: false
  prob_include_video_ref_img: 0.0
  allow_k_angles_near_the_front: 90
  
  # 其他配置
  test_mode: false
  load_test_data: true 

  # dataset specific parameters
  flat_hand_mean: false
  num_expression_coeffs: 10