model:
  sapiens_encoder:
    image_feature_dim: 1536
    sapiens_model_name: "/disk2/liubingqi/audio2avatar/gaussian_avatar/sapiens/sapiens_lite_host/torchscript/pretrain/checkpoints/sapiens_1b/sapiens_1b_epoch_173_torchscript.pt2"
    sapiens_freeze: true
    sapiens_resolution: 1024
    sapiens_antialias: true
    sapiens_encoder_feat_dim: 384
