training:
  max_epochs: 500
  batch_size: 1
  learning_rate: 5e-5
  total_steps: 50000
  gradient_accumulate_steps: 4

  optimizer:
    type: "Adam"
    weight_decay: 0.0
    betas: [0.9, 0.999]

  scheduler:
    type: "LinearLR"
    start_factor: 1.0
    end_factor: 0.1

  dataloader:
    num_workers: 4
    pin_memory: true
    shuffle: true

  validation:
    val_every_n_epoch: 1
    save_top_k: 1
    monitor: "val/loss_total"
    mode: "min"

  logging:
    log_every_n_steps: 10
    use_wandb: false
    wandb_project: "audio_motion_avatar"
    wandb_run_name: null

  output_dir: "outputs_reconstruction_84"
  experiment_name: "triplane_reconstruction"

  device: "cuda"
  devices: 1
  strategy: "ddp"
  accelerator: "gpu"

  seed: 41

  resume: false
  ckpt: "/home/liubingqi/work/audio_motion_avatar/outputs_reconstruction_729/checkpoints/last.ckpt"

  fast_dev_run: false